sudo: false
language: node_js
node_js:
  - 0.10
  - 0.12
  - 4
  - 5
  - 6
matrix:
    allow_failures:
        - node_js: 4
        - node_js: 5
        - node_js: 6
env:
  global:
    - CXX=g++-4.8
script: "npm run travis"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
